package ken.event;

import ken.event.validator.BaseValidator;
import ken.event.validator.EventValidator;
import ken.event.meta.AtomicE;

/**
 * This is a basic event, actually it is an event container.
 * 
 * @author KennyZJ
 * 
 */
public class Event<T> implements java.io.Serializable {

	private static final long serialVersionUID = 6498384063284494738L;

	private Object eventID; // generated by client and never conflict with each
							// other
	private String evtType; // if eventType is not set by constructor, make sure
							// it's not null
	private long awaredTS; // the timestamp when the event is awared by the
							// sensor
	private String location; // the physical address event is awared

	private String source; // only registered source can create event
	private String securityKey; // need credential of the privilege

	private T evtData; // the actual business information about the event,
						// payload of it

	private Actor producer; // the event producer is some kind of actor, for
							// instance A Client Java Process

	public Event(String evtType, long awaredTS, String location, String source,
			String securityKey, T evtData, Actor producer) {
		if (evtType != null && !"".equals(evtType)) {
			this.evtType = evtType;
		} else {
			((AtomicE) evtData).getType();
		}
		this.awaredTS = awaredTS;
		this.location = location;
		this.source = source;
		this.securityKey = securityKey;
		this.evtData = evtData;
		this.producer = producer;

	}

	public Object getEventID() {
		return eventID;
	}

	public String getEvtType() {
		return evtType;
	}

	public long getAwaredTS() {
		return awaredTS;
	}

	public String getLocation() {
		return location;
	}

	public String getSource() {
		return source;
	}

	public String getSecurityKey() {
		return securityKey;
	}

	public T getEvtData() {
		return evtData;
	}

	public Actor getProducer() {
		return producer;
	}

	public void setEventID(Object eventID) {
		this.eventID = eventID;
	}

	public void setEvtType(String evtType) {
		this.evtType = evtType;
	}

	public void setAwaredTS(long awaredTS) {
		this.awaredTS = awaredTS;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public void setSecurityKey(String securityKey) {
		this.securityKey = securityKey;
	}

	public void setEvtData(T evtData) {
		this.evtData = evtData;
	}

	public void setProducer(Actor producer) {
		this.producer = producer;
	}

	public boolean validate() {
		EventValidator ev = new BaseValidator();
		return ev.validate();
	}

}
